import "server-only";

/**
 * Server-only PDF renderer for M5A order documents (order request /
 * delivery note / invoice DRAFT). Runs on the Node runtime only.
 *
 * ⚠️ LEGAL (docs/DOCUMENTS_AND_INVOICES_GUIDE.md): an invoice draft is a
 * DRAFT PREVIEW — never a legal tax invoice. This renderer ALWAYS stamps a
 * DRAFT watermark + the localized not-a-tax-invoice notice on invoice
 * drafts, and every document carries the "generated by Madaf · not a tax
 * invoice" footer. Do not remove them.
 *
 * Engine: pdfkit + fontkit with a vendored OFL Rubik TTF (Latin + Hebrew +
 * Arabic + ₪). Pure JS, no native/binary download — chosen for the repo's
 * offline/local-only, low-dependency posture (see M5A report). Hebrew and
 * English render perfectly; Arabic is best-effort (fontkit shapes the
 * glyphs; full mixed-direction bidi polish is tracked for M5B). pdfkit is
 * listed in serverExternalPackages so its font/AFM fs reads keep working.
 */
import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import { dirFor, type Locale } from "@/i18n/config";
import { getDictionary } from "@/i18n/dictionaries";
import { formatCurrency, formatDateLong } from "@/lib/format";
import type { DocumentType } from "@/lib/types";
import type { OrderDocumentSource } from "./document-model";

// pdfkit draws to a raw canvas — literal colors are required here (the
// Tailwind "no raw hex" rule governs UI, not a PDF). These mirror the
// design-system tokens in src/app/globals.css.
const COLOR = {
  ink: "#211e1b",
  inkSoft: "#57524c",
  inkMuted: "#8a847c",
  brand: "#175f58",
  line: "#e7e3dd",
  danger: "#b42318",
} as const;

const FONT_DIR = path.join(process.cwd(), "src", "lib", "pdf", "fonts");
let CACHED_FONTS: { regular: Buffer; bold: Buffer } | null = null;
function loadFonts() {
  if (!CACHED_FONTS) {
    CACHED_FONTS = {
      regular: fs.readFileSync(path.join(FONT_DIR, "Rubik-Regular.ttf")),
      bold: fs.readFileSync(path.join(FONT_DIR, "Rubik-Bold.ttf")),
    };
  }
  return CACHED_FONTS;
}

export interface RenderDocumentInput {
  source: OrderDocumentSource;
  docType: DocumentType;
  /** Internal document number (DOC-####-x) — NOT a legal tax sequence. */
  docNumber: string;
  /** ISO date the document row was recorded. */
  docDate: string;
  /** Language the document renders in (Hebrew-first default upstream). */
  docLocale: Locale;
}

type Align = "start" | "center" | "end";

/**
 * Render an order document to a PDF byte array. Resolves once pdfkit has
 * flushed the whole stream.
 */
export function renderOrderDocumentPdf(
  input: RenderDocumentInput,
): Promise<Uint8Array<ArrayBuffer>> {
  const { source, docType, docNumber, docDate, docLocale } = input;
  const dict = getDictionary(docLocale);
  const t = dict.docs;
  const rtl = dirFor(docLocale) === "rtl";
  const isInvoiceDraft = docType === "invoiceDraft";
  const isDelivery = docType === "delivery";
  const showPrices = !isDelivery;

  const fonts = loadFonts();
  const doc = new PDFDocument({ size: "A4", margin: 40, autoFirstPage: false });
  doc.registerFont("body", fonts.regular);
  doc.registerFont("bold", fonts.bold);

  const chunks: Buffer[] = [];
  const done = new Promise<Uint8Array<ArrayBuffer>>((resolve, reject) => {
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => {
      const merged = Buffer.concat(chunks);
      // Fresh ArrayBuffer-backed copy so the bytes are a valid Response body.
      const out = new Uint8Array(merged.byteLength);
      out.set(merged);
      resolve(out);
    });
    doc.on("error", reject);
  });

  const M = 40;
  const left = M;
  const pageW = 595.28; // A4 width in pt (portrait)
  const contentRight = pageW - M;
  const contentW = contentRight - left;

  const startAlign = rtl ? "right" : "left";
  const endAlign = rtl ? "left" : "right";
  const pdfAlign = (a: Align): "left" | "right" | "center" =>
    a === "center" ? "center" : a === "start" ? startAlign : endAlign;

  // ── Watermark + footer on every page (drawn before content → behind it) ──
  const drawChrome = () => {
    const w = doc.page.width;
    const h = doc.page.height;
    if (isInvoiceDraft) {
      doc.save();
      doc.rotate(-30, { origin: [w / 2, h / 2] });
      doc
        .font("bold")
        .fontSize(120)
        .fillColor(COLOR.danger)
        .opacity(0.06)
        .text(t.draftWatermark, w / 2 - 300, h / 2 - 70, {
          width: 600,
          align: "center",
        });
      doc.restore();
      doc.opacity(1);
    }
    // Universal footer: generated by Madaf · internal · not a tax invoice.
    const fy = h - M - 14;
    doc
      .moveTo(M, fy - 6)
      .lineTo(w - M, fy - 6)
      .lineWidth(0.5)
      .strokeColor(COLOR.line)
      .stroke();
    doc
      .font("body")
      .fontSize(7.5)
      .fillColor(COLOR.inkMuted)
      .text(t.pdfFooter, M, fy, { width: w - 2 * M, align: "center" });
  };
  doc.on("pageAdded", drawChrome);
  doc.addPage();

  // Strip bidi control/format marks (LRM/RLM/ALM/isolates/overrides) that
  // Intl.NumberFormat/DateTimeFormat insert and Rubik has no glyph for —
  // otherwise they render as tofu boxes around every currency/date value.
  const clean = (str: string): string => {
    let out = "";
    for (const ch of str ?? "") {
      const c = ch.codePointAt(0) ?? 0;
      const bidi =
        c === 0x200e ||
        c === 0x200f ||
        c === 0x061c ||
        (c >= 0x202a && c <= 0x202e) ||
        (c >= 0x2066 && c <= 0x2069) ||
        c === 0xfeff;
      if (!bidi) out += ch;
    }
    return out;
  };

  // ── small helpers ────────────────────────────────────────────────────────
  const text = (
    str: string,
    x: number,
    y: number,
    w: number,
    opts: { size?: number; bold?: boolean; color?: string; align?: Align } = {},
  ): number => {
    doc
      .font(opts.bold ? "bold" : "body")
      .fontSize(opts.size ?? 9)
      .fillColor(opts.color ?? COLOR.ink)
      .text(clean(str), x, y, { width: w, align: pdfAlign(opts.align ?? "start") });
    return doc.y;
  };
  const rule = (y: number, color: string = COLOR.line, weight = 1) => {
    doc.moveTo(left, y).lineTo(contentRight, y).lineWidth(weight).strokeColor(color).stroke();
  };

  const half = contentW / 2;
  const startBox = rtl ? { x: left + half, w: half } : { x: left, w: half };
  const endBox = rtl ? { x: left, w: half } : { x: left + half, w: half };

  // ── Header: supplier identity (start) + document meta (end) ──────────────
  const yTop = M + 6;
  let yS = text(source.supplier.name[docLocale], startBox.x, yTop, startBox.w, {
    size: 18,
    bold: true,
    color: COLOR.brand,
    align: "start",
  });
  if (source.supplier.legalName) {
    yS = text(source.supplier.legalName, startBox.x, yS + 1, startBox.w, {
      size: 8.5,
      color: COLOR.inkMuted,
      align: "start",
    });
  }
  if (source.supplier.companyId) {
    yS = text(
      `${t.supplierIdLabel}: ${source.supplier.companyId}`,
      startBox.x,
      yS,
      startBox.w,
      { size: 8.5, color: COLOR.inkMuted, align: "start" },
    );
  }

  let yE = text(t.types[docType], endBox.x, yTop, endBox.w, {
    size: 16,
    bold: true,
    color: COLOR.ink,
    align: "end",
  });
  yE = text(`${t.docNumber}: ${docNumber}`, endBox.x, yE + 2, endBox.w, {
    size: 9,
    color: COLOR.inkSoft,
    align: "end",
  });
  yE = text(`${t.orderRef}: ${source.orderNumber}`, endBox.x, yE, endBox.w, {
    size: 9,
    color: COLOR.inkSoft,
    align: "end",
  });
  yE = text(
    `${t.docDate}: ${formatDateLong(docDate, docLocale)}`,
    endBox.x,
    yE,
    endBox.w,
    { size: 9, color: COLOR.inkSoft, align: "end" },
  );

  let y = Math.max(yS, yE) + 8;
  rule(y, COLOR.brand, 2);
  y += 14;

  // ── Parties: supplier + bill-to ──────────────────────────────────────────
  const partyHeading = (label: string, x: number, w: number, yy: number) =>
    text(label.toUpperCase(), x, yy, w, {
      size: 7.5,
      bold: true,
      color: COLOR.inkMuted,
      align: "start",
    });

  let ySa = partyHeading(t.supplier, startBox.x, startBox.w, y);
  ySa = text(source.supplier.name[docLocale], startBox.x, ySa + 1, startBox.w, {
    size: 9.5,
    bold: true,
    align: "start",
  });
  if (source.supplier.address[docLocale]) {
    ySa = text(source.supplier.address[docLocale], startBox.x, ySa, startBox.w, {
      size: 9,
      color: COLOR.inkSoft,
      align: "start",
    });
  }
  if (source.supplier.phone) {
    ySa = text(source.supplier.phone, startBox.x, ySa, startBox.w, {
      size: 9,
      color: COLOR.inkSoft,
      align: "start",
    });
  }

  let yEa = partyHeading(t.billTo, endBox.x, endBox.w, y);
  yEa = text(source.customer?.name ?? "—", endBox.x, yEa + 1, endBox.w, {
    size: 9.5,
    bold: true,
    align: "start",
  });
  if (source.customer) {
    yEa = text(source.customer.city[docLocale], endBox.x, yEa, endBox.w, {
      size: 9,
      color: COLOR.inkSoft,
      align: "start",
    });
    if (source.customer.phone) {
      yEa = text(source.customer.phone, endBox.x, yEa, endBox.w, {
        size: 9,
        color: COLOR.inkSoft,
        align: "start",
      });
    }
    if (source.customer.contactName) {
      yEa = text(source.customer.contactName, endBox.x, yEa, endBox.w, {
        size: 9,
        color: COLOR.inkSoft,
        align: "start",
      });
    }
  }

  y = Math.max(ySa, yEa) + 16;

  // ── Items table ──────────────────────────────────────────────────────────
  interface Col {
    key: "item" | "qty" | "unit" | "price" | "total";
    w: number;
    align: Align;
    label: string;
  }
  const cols: Col[] = showPrices
    ? [
        { key: "item", w: contentW * 0.42, align: "start", label: t.colItem },
        { key: "qty", w: contentW * 0.1, align: "center", label: t.colQty },
        { key: "unit", w: contentW * 0.18, align: "start", label: t.colUnit },
        { key: "price", w: contentW * 0.15, align: "end", label: t.colUnitPrice },
        { key: "total", w: contentW * 0.15, align: "end", label: t.colTotal },
      ]
    : [
        { key: "item", w: contentW * 0.6, align: "start", label: t.colItem },
        { key: "qty", w: contentW * 0.15, align: "center", label: t.colQty },
        { key: "unit", w: contentW * 0.25, align: "start", label: t.colUnit },
      ];

  // Physical boxes: LTR left→right, RTL right→left (logical col 0 at the edge).
  const boxes: { x: number; w: number; align: Align }[] = [];
  if (!rtl) {
    let x = left;
    for (const c of cols) {
      boxes.push({ x, w: c.w, align: c.align });
      x += c.w;
    }
  } else {
    let x = contentRight;
    for (const c of cols) {
      x -= c.w;
      boxes.push({ x, w: c.w, align: c.align });
    }
  }

  const drawHeaderRow = (yy: number): number => {
    cols.forEach((c, i) => {
      text(c.label.toUpperCase(), boxes[i].x + 2, yy, boxes[i].w - 4, {
        size: 7.5,
        bold: true,
        color: COLOR.inkMuted,
        align: c.align,
      });
    });
    const yb = yy + 15;
    rule(yb - 2, COLOR.line, 1);
    return yb;
  };

  y = drawHeaderRow(y);

  const pageBottom = doc.page.height - M - 28; // leave room for footer
  for (const item of source.items) {
    const values: Record<Col["key"], string> = {
      item: item.name[docLocale] || item.name.he || "",
      qty: String(item.quantity),
      unit: `${dict.packaging[item.packageUnit]} · ${item.packageQuantity}`,
      price: formatCurrency(item.unitPrice, docLocale),
      total: formatCurrency(item.lineTotal, docLocale),
    };
    // Row height driven by the (wrappable) item-name cell.
    doc.font("body").fontSize(9);
    const nameH = doc.heightOfString(values.item, {
      width: (showPrices ? contentW * 0.42 : contentW * 0.6) - 4,
    });
    const rowH = Math.max(nameH, 12) + 8;
    if (y + rowH > pageBottom) {
      doc.addPage();
      y = M + 6;
      y = drawHeaderRow(y);
    }
    cols.forEach((c, i) => {
      text(values[c.key], boxes[i].x + 2, y, boxes[i].w - 4, {
        size: 9,
        color: c.key === "total" ? COLOR.ink : COLOR.inkSoft,
        bold: c.key === "total",
        align: c.align,
      });
    });
    y += rowH;
    rule(y - 2, COLOR.line, 0.5);
  }

  y += 8;

  // ── Totals (order request + invoice draft only; delivery hides prices) ───
  if (showPrices) {
    const boxW = 220;
    const bx = rtl ? left : contentRight - boxW;
    const totRow = (label: string, value: string, opts: { bold?: boolean; size?: number } = {}) => {
      const yy = y;
      text(label, bx, yy, boxW, {
        size: opts.size ?? 9,
        bold: opts.bold,
        color: opts.bold ? COLOR.ink : COLOR.inkSoft,
        align: "start",
      });
      text(value, bx, yy, boxW, {
        size: opts.size ?? 9,
        bold: opts.bold,
        color: opts.bold ? COLOR.ink : COLOR.inkSoft,
        align: "end",
      });
      y = yy + (opts.size ?? 9) + 6;
    };
    totRow(t.subtotal, formatCurrency(source.totals.subtotal, docLocale));
    totRow(t.vatEstimate, formatCurrency(source.totals.vatTotal, docLocale));
    rule(y - 2, COLOR.brand, 1.5);
    y += 3;
    totRow(t.totalEstimate, formatCurrency(source.totals.total, docLocale), {
      bold: true,
      size: 11,
    });
    y = text(t.vatDisclaimer, bx, y + 2, boxW, {
      size: 7.5,
      color: COLOR.inkMuted,
      align: "start",
    });
    y += 10;
  }

  // ── Notes ────────────────────────────────────────────────────────────────
  if (source.notes) {
    y = text(source.notes, left, y + 4, contentW, {
      size: 9,
      color: COLOR.inkSoft,
      align: "start",
    });
    y += 8;
  }

  // ── Delivery signature block ─────────────────────────────────────────────
  if (isDelivery) {
    y += 24;
    if (y > pageBottom - 40) {
      doc.addPage();
      y = M + 6;
    }
    text(t.receivedBy, startBox.x, y, startBox.w - 20, {
      size: 9,
      color: COLOR.inkMuted,
      align: "start",
    });
    text(t.signature, endBox.x, y, endBox.w - 20, {
      size: 9,
      color: COLOR.inkMuted,
      align: "start",
    });
    const ly = y + 28;
    doc.moveTo(startBox.x, ly).lineTo(startBox.x + startBox.w - 30, ly).lineWidth(0.75).strokeColor(COLOR.inkMuted).stroke();
    doc.moveTo(endBox.x, ly).lineTo(endBox.x + endBox.w - 30, ly).lineWidth(0.75).strokeColor(COLOR.inkMuted).stroke();
    y = ly + 10;
  }

  // ── Invoice-draft not-legal notice, inside the sheet (never removed) ─────
  if (isInvoiceDraft) {
    if (y > pageBottom - 48) {
      doc.addPage();
      y = M + 6;
    }
    y += 6;
    rule(y, COLOR.line, 0.5);
    text(t.notLegalNotice, left, y + 6, contentW, {
      size: 8,
      color: COLOR.danger,
      align: "start",
    });
  }

  doc.end();
  return done;
}
