-- ═══════════════════════════════════════════════════════════════════════
-- Madaf M7E — customer-facing public order reference
--
-- orders.order_number is a SEQUENTIAL internal number ('MDF-1', 'MDF-2', …)
-- used by the warehouse/admin. Showing it to customers leaks order volume and
-- is guessable. This adds a RANDOM, non-sequential, per-tenant-unique
-- public_ref ('MDF-XXXXXXXX') that customer-facing surfaces show instead. The
-- internal order_number is unchanged (admin sorting/search unaffected).
--
-- Generated by a BEFORE INSERT trigger so EVERY order (any path) gets one,
-- without touching the order-create RPC bodies. No RLS/grants change; the
-- customer never receives the internal sequential number.
-- ═══════════════════════════════════════════════════════════════════════

alter table public.orders add column public_ref text;

-- Random ref: 'MDF-' + 8 chars from an unambiguous alphabet (no I/L/O/0/1).
-- ~30^8 ≈ 6.6e11 space; the trigger/backfill retry on the unique index.
create or replace function public._gen_order_public_ref()
returns text
language sql
volatile
set search_path = ''
as $$
  select 'MDF-' || string_agg(
    substr('ABCDEFGHJKMNPQRSTUVWXYZ23456789',
           (floor(random() * 30) + 1)::int, 1), '')
  from generate_series(1, 8);
$$;

comment on function public._gen_order_public_ref() is
  'M7E: a random, non-sequential customer order reference (MDF-XXXXXXXX). Uniqueness enforced per tenant by the caller/trigger + unique index.';

-- BEFORE INSERT: assign a unique public_ref if one was not supplied.
create or replace function public._orders_set_public_ref()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.public_ref is null or trim(new.public_ref) = '' then
    loop
      new.public_ref := public._gen_order_public_ref();
      exit when not exists (
        select 1 from public.orders o
        where o.tenant_id = new.tenant_id and o.public_ref = new.public_ref);
    end loop;
  end if;
  return new;
end;
$$;

create trigger orders_set_public_ref
  before insert on public.orders
  for each row execute function public._orders_set_public_ref();

-- Backfill existing orders with a unique per-tenant ref.
do $$
declare
  r record;
  v_ref text;
begin
  for r in select id, tenant_id from public.orders where public_ref is null loop
    loop
      v_ref := public._gen_order_public_ref();
      exit when not exists (
        select 1 from public.orders o
        where o.tenant_id = r.tenant_id and o.public_ref = v_ref);
    end loop;
    update public.orders set public_ref = v_ref where id = r.id;
  end loop;
end;
$$;

alter table public.orders alter column public_ref set not null;

create unique index orders_tenant_public_ref_key
  on public.orders (tenant_id, public_ref);

-- ── Customer-facing token order RPC returns the PUBLIC ref ────────────────
-- Same signature (returns table (order_number text)); the value it returns is
-- now the random public_ref, so the private-shop success screen shows the
-- customer a non-sequential reference instead of the internal MDF-N number.
create or replace function public.create_order_request_from_token(
  p_token text,
  p_items jsonb,
  p_notes text default null
)
returns table (order_number text)
language plpgsql volatile security definer set search_path = ''
as $$
declare
  v_tenant uuid;
  v_customer uuid;
  v_link uuid;
  v_order_id uuid;
  v_public_ref text;
begin
  select tenant_id, customer_id, link_id into v_tenant, v_customer, v_link
  from public._resolve_token(p_token);

  select o.order_id into v_order_id
  from public._order_create_core(v_tenant, p_items, v_customer, p_notes, 'remote_customer') o;

  -- Customer sees the random public reference, NOT the internal sequence.
  select public_ref into v_public_ref from public.orders where id = v_order_id;

  update public.customer_access_links set last_used_at = now() where id = v_link;
  return query select v_public_ref;
end;
$$;

revoke all on function public.create_order_request_from_token(text, jsonb, text) from public;
grant execute on function public.create_order_request_from_token(text, jsonb, text)
  to anon, authenticated, service_role;
